### ISSUE TITLE
Error using Map Example 

### ISSUE THREAD

**Issue by JeremyBYU** [noxdafox/pebble#21] opened 2018-02-03 17:31 UTC
OS: Windows 10 X64
Python Version: 3.5.4 from Anaconda

Example: 

```
from concurrent.futures import TimeoutError
from pebble import ProcessPool, ProcessExpired

def function(n):
    return n

with ProcessPool() as pool:
    future = pool.map(function, range(100), timeout=10)

    iterator = future.result()

    while True:
        try:
            result = next(iterator)
        except StopIteration:
            break
        except TimeoutError as error:
            print("function took longer than %d seconds" % error.args[1])
        except ProcessExpired as error:
            print("%s. Exit code: %d" % (error, error.exitcode))
        except Exception as error:
            print("function raised %s" % error)
            print(error.traceback)  # Python's traceback of remote process
```

Error: `AttributeError: Can't get attribute 'function' on <module '__main__' (built-in)>`

Stack Trace for one of the processes: 
```
Process Process-3:
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\process.py", line 383, in worker_process
    for task in worker_get_next_task(channel, params.max_tasks):
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\process.py", line 398, in worker_get_next_task
    yield fetch_task(channel)
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\process.py", line 404, in fetch_task
    return task_transaction(channel)
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\process.py", line 383, in worker_process
    for task in worker_get_next_task(channel, params.max_tasks):
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\process.py", line 413, in task_transaction
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\process.py", line 398, in worker_get_next_task
    yield fetch_task(channel)
    task = channel.recv()
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\process.py", line 404, in fetch_task
    return task_transaction(channel)
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\channel.py", line 90, in recv
    return self.reader.recv()
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\process.py", line 413, in task_transaction
    task = channel.recv()
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\multiprocessing\connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\site-packages\pebble\pool\channel.py", line 90, in recv
    return self.reader.recv()
AttributeError: Can't get attribute 'function' on <module '__main__' (built-in)>
  File "C:\Users\Jerem\Anaconda3\envs\airsim\lib\multiprocessing\connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'function' on <module '__main__' (built-in)>
```

What my end game of using pebble will be (not necessarily from example):
Map  a list of arguments to function call using a multiprocessing pool.   Have a global timeout.  If time runs out, the returns from the function calls (though incomplete)  are still valuable and should be saved and further processed in the main process.

Thanks for your help and this great package.

**Comment by noxdafox** [comment] 2018-02-03 17:48
Hi @JeremyBYU, 

I believe you are affected by the following bug: https://bugs.python.org/issue25053

`Pebble` simply wraps the `multiprocessing` facilities. Therefore most of the limitations of the latter affect the library as well.

As a general guideline, with `multiprocessing` is always preferable to ensure [the module is importable](https://docs.python.org/3.4/library/multiprocessing.html#the-spawn-and-forkserver-start-methods) without side effects. In your case, importing the module will actually execute the entire logic.

If you modify the logic as follows, does the error still show?

```python
from concurrent.futures import TimeoutError
from pebble import ProcessPool, ProcessExpired

def function(n):
    return n

def main():
    with ProcessPool() as pool:
        future = pool.map(function, range(100), timeout=10)

        iterator = future.result()

        while True:
            try:
                result = next(iterator)
            except StopIteration:
                break
            except TimeoutError as error:
                print("function took longer than %d seconds" % error.args[1])
            except ProcessExpired as error:
                print("%s. Exit code: %d" % (error, error.exitcode))
            except Exception as error:
                print("function raised %s" % error)
                print(error.traceback)  # Python's traceback of remote process

if __name__ == '__main__':
    main()
```

**Comment by JeremyBYU** [comment] 2018-02-03 18:50
I think that fixed the big issue. I copy and pasted the code exactly as you have shown and ran it directly (as a script).  It seemed to work but I have a final error:

```
98
99
RuntimeError: I/O operations still in flight while destroying Overlapped object, the process may crash
```

Also do you support [starmap](https://docs.python.org/3.4/library/multiprocessing.html#multiprocessing.pool.Pool.starmap)?

**Comment by noxdafox** [comment] 2018-02-03 20:54
That's very curious error message indeed! It seems due to some changes applied in the most recent versions of Python on version of Windows greater than XP. More info [here](https://bugs.python.org/issue19565).

It is most likely happening during the `Pool` shutdown process (proof is your example computes all the tasks correctly) and it's most likely noise. I will investigate further and silence the noise. For the time being, you can safely ignore it.

Regarding `starmap` support, `Pebble` doesn't expose that functionality as I never being asked for and never felt the need for it (below further explanations). Patches are more than welcome.

For the last point (global timeout), you can easily implement that yourself. All Python `pool.map` implementations (`multiprocessing` and `concurrent.futures`) are simple convenience wrapper on top of `apply`, `submit` or `schedule` methods (that's why I did not bother providing all `map` functions).

As `Pebble` functions return subclasses of `concurrent.future.Future` objects, you can use the official facilities to implement the logic yourself.

```python
global_timeout = 10
my_iterable = [1, 2, 3]

futures = [pool.schedule(function, args=[value]) for value in my_iterable]
completed, pending = concurrent.futures.wait(futures, timeout=global_timeout)

# cancel pending futures, stop workers if they are already processing them
for future in pending:
    future.cancel()
```

**Comment by JeremyBYU** [comment] 2018-02-03 21:17
Thank you for taking the time to look into this, I really appreciate it. Everything seems to be working fine now. Here is the final code I'm using for a full example of problem statement: process as many jobs as fast as I can under a time limit and retrieve the results of the finished jobs.

```python
import numpy as np
import time
import concurrent
from pebble import ProcessPool

JOBS = 10
GLOBAL_TIMEOUT = 2
def worker(uid):
    "uid specified the unique id of this job"
    xtime = np.random.random()*2
    print("will sleep ", xtime)
    time.sleep(xtime)
    return (uid, xtime)

def main():
    with ProcessPool(4) as pool:
        futures = [pool.schedule(worker, args=[value]) for value in range(JOBS)]
        completed, pending = concurrent.futures.wait(futures, timeout=GLOBAL_TIMEOUT)
        # cancel pending futures, stop workers if they are already processing them
        for future in pending:
            future.cancel()
        # print out which jobs were completed. Its important to know the job id.
        print('Completed Jobs {}/{}: {}'.format(len(completed), JOBS, [job.result() for job in completed]))

if __name__ == "__main__":
    main()
```

Thanks again!

**Comment by noxdafox** [comment] 2018-02-03 21:21
Np, glad the library is being of help.

In the next days I will fix the spurious error message and complete the documentation examples so they won't be misleading any more.

I will close this issues once the changes will be published.

**Comment by JeremyBYU** [comment] 2018-02-04 03:43
Sorry to bother but I did have some questions.  It seems that 'cancelling' a future is not working the way I am expecting.  In attached code only 4 jobs complete in time as I waited only a max of 2 seconds globally. However the other jobs that are to be *cancelled* finish (read execute) **very** quickly, meaning they are not sleeping  however I still see the jobs print statement. I was just not expecting to see any of their work print statements, why is it that I see them?

I also have variants of this where I actually do a heavy load of CPU work and it *sometimes*  shutdowns the work in Windows (always works on Linux Ubuntu) when cancelled, but I *still* see the print statements (in both OS's). 

This really isn't a deal breaker for me, but you seem to be very knowledgeable about this and might know what is occurring. No rush or expectation on a response. 

Thanks!

Here's an example with the sleep being constant to make things simpler.
```python
import time
import concurrent
from pebble import ProcessPool

JOBS = 20
GLOBAL_TIMEOUT = 2
def worker(uid):
    "uid specified the unique id of this job"
    print("sleep ", uid)
    time.sleep(1)
    return (uid)

def main():
    with ProcessPool(4) as pool:
        futures = [pool.schedule(worker, args=[value]) for value in range(JOBS)]
        completed, pending = concurrent.futures.wait(futures, timeout=GLOBAL_TIMEOUT)

        # cancel pending futures, stop workers if they are already processing them
        for future in pending:
            future.cancel()
        
        print('Completed Jobs {}/{}: {}'.format(len(completed), JOBS, [job.result() for job in completed]))

if __name__ == "__main__":
    main()
```

```
sleep  0
sleep  1
sleep  2
sleep  3
sleep  4
sleep  5
sleep  6
sleep  7
Completed Jobs 4/20: [1, 0, 2, 3]
sleep  8
sleep  9
sleep  10
sleep  11
sleep  12
sleep  13
sleep  14
sleep  15
sleep  16
sleep  17
sleep  18
sleep  19
RuntimeError: I/O operations still in flight while destroying Overlapped object, the process may crash
```

**Comment by noxdafox** [comment] 2018-02-04 20:54
This is expected behaviour and to understand it we need to dive a bit in the `Pool` internals.

Futures scheduled to the pool are fed to the worker via a `Pipe`. In order to maximise the performance, the logic must ensure the workers always have available work on the `Pipe`. This means we push as many futures down the `Pipe` as they fit.  

Pipes work pretty much like sockets: once you push something down them, you cannot change it any more. 
 
If you cancel a `Future` which has already been put on the `Pipe`, there is no way to notify the worker that it has been cancelled in the main process. The simple and most reliable solution is to kill the worker once it picks up the task.

As this is an asynchronous operation, the worker might actually start processing the job before the kill request is delivered. Hence, you see the print message. If you switch the print statement after the sleep function, you won't see the log lines any more.

**Comment by JeremyBYU** [comment] 2018-02-04 21:31
Okay thanks for the explanation. I’m wondering what I would need to change to prevent the job from even starting.  Is there a way to limit the number of tasks allowed in the Pipe, that way multiple jobs don’t need to be started just to be cancled?  Maybe the parameter max_tasks? This way you can cancel the many leftover jobs before they are put in the Pipe?

**Comment by noxdafox** [comment] 2018-02-07 13:09
Due to the asynchronous nature of the problem, you cannot reliably ensure it won't happen. There are mitigations you can try but they all come with a cost.

One thing would be abruptly killing the `Pool`.

```python
pool = ProcessPool()
completed, pending = concurrent.futures.wait(futures, timeout=GLOBAL_TIMEOUT)

if pending:
    # the pool becomes unusable from now on, create a new one
    pool.stop()
    pool.join()  
```

My bet is you'll still see some message printed.

Another would be to signal to the function itself to give up. This is ugly, resource expensive and deadlock prone so I'd really recommend against.

```python
from multiprocessing import Event

def worker(uid, cancelled_event):
    # if the Event is set, it means the task has been cancelled, give up
    if cancelled_event.is_set():  # 
        return

    ...

def callback(future):
    """If the future was cancelled, we signal to the child process not to pick the job up."""
    if future.cancelled():
        future.cancelled_event.set()

futures = []
for value in range(JOBS):    
    cancelled_event = Event()  # we use a process Event to signal whether the future was cancelled, this is heavy
    future = pool.schedule(worker, args=(value, event)) 
    future.cancelled_event = cancelled_event  
    future.add_done_callback(callback)

completed, pending = concurrent.futures.wait(futures, timeout=GLOBAL_TIMEOUT)
for future in pending:
    future.cancel()
```
NOTE: I am ashamed of the code I just wrote :D

**Comment by JeremyBYU** [comment] 2018-02-08 13:42
Wow, alot more complicated than I thought it would be! Thank your for your help and expertise.  Just for fun, I'll try out a few of your ideas and see how they perform.

Thanks again!

**Comment by noxdafox** [comment] 2018-02-28 19:32
@JeremyBYU the `RuntimeError` should be silenced in version 4.3.7.

**Comment by noxdafox** [comment] 2018-03-04 10:10
Closing this issue.

**Closed by noxdafox** 2018-03-04 10:10 UTC
