### ISSUE TITLE
FileNotFoundError During Installation

### ISSUE THREAD

**Issue by KySmith1** [noxdafox/pebble#53] opened 2020-01-13 23:30 UTC
### Version Info
Package Versions:
Pebble version: v4.4.1

Environment Versions:
Docker Image: python:3.6-alpine
Gitlab Runner Version: gitlab-runner 11.10.1

### Expected Behavior
Pebble installs on docker image has occurred in 4.4.0.

### Actual Behavior
```
Collecting pebble==4.4.1
  Downloading https://files.pythonhosted.org/packages/5e/a3/16f98c868854a6916d68bb6ea02edcf7c91021ad41892862f1307c6831df/Pebble-4.4.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xx5yp0kw/pebble/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xx5yp0kw/pebble/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xx5yp0kw/pebble/pip-egg-info
         cwd: /tmp/pip-install-xx5yp0kw/pebble/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xx5yp0kw/pebble/setup.py", line 39, in <module>
        version="{}".format(package_version()),
      File "/tmp/pip-install-xx5yp0kw/pebble/setup.py", line 14, in package_version
        version = read_version(version_path)
      File "/tmp/pip-install-xx5yp0kw/pebble/setup.py", line 22, in read_version
        return subprocess.check_output(('git', 'describe')).rstrip().decode()
      File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/local/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### Steps to Reproduce
(some may be extraneous)
1. Pull & Run python:3.6-alpine docker image
`docker pull python:3.6-alpine && docker run -it python:3.6-alpine sh`
2. Attempt to install pebble
`pip install pebble==4.4.1`

**Comment by noxdafox** [comment] 2020-01-25 10:15
Thanks for the good bug report!

This is actually a duplicate of #51. Closing it as duplicate.

**Closed** 2020-01-25 10:15 UTC
Labels: bug, duplicate

**Comment by noxdafox** [comment] 2020-01-26 10:52
Release `4.5.0` should address this issue. Please re-open this ticket if not.
