### ISSUE TITLE
ProcessPool issue : error: (9, 'Bad file descriptor')

### ISSUE THREAD

**Issue by pw717** [noxdafox/pebble#10] opened 2017-06-06 14:44 UTC
Hello again.
An other issue with the example : (4.2.1 and moc osx 10.12.5).
I cannot go threw the example on https://pypi.python.org/pypi/Pebble, see code below 

```python
def function(foo, bar=0):
    return foo + bar

def task_done(future):
    try:
        result = future.result()  # blocks until results are ready
    except Exception as error:
        print("Function raised %s" % error)
        print(error.traceback)  # traceback of the function
    except TimeoutError as error:
        print("Function took longer than %d seconds" % error.args[1])

with ProcessPool(max_workers=5, max_tasks=10) as pool:
    for i in range(0, 10):
        future = pool.schedule(function, args=[i], timeout=3)
        future.add_done_callback(task_done)
```

It gives at the end of exectution :

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/pebble/pool/process.py", line 155, in message_manager_loop
    pool_manager.process_next_message(SLEEP_UNIT)
  File "/usr/local/lib/python2.7/site-packages/pebble/pool/process.py", line 184, in process_next_message
    message = self.worker_manager.receive(timeout)
  File "/usr/local/lib/python2.7/site-packages/pebble/pool/process.py", line 304, in receive
    if self.pool_channel.poll(timeout):
  File "/usr/local/lib/python2.7/site-packages/pebble/pool/channel.py", line 44, in unix_poll
    return bool(select([self.reader], [], [], timeout)[0])
error: (9, 'Bad file descriptor')
```
Thank you again in advance for youy help ! :-)

**Comment by noxdafox** [comment] 2017-06-12 20:11
Hi, I'm trying to get my hands on a MAC so I can try to reproduce the issue. Will come back once I succeed.

**Comment by noxdafox** [comment] 2017-07-19 19:52
Some updates: I did not manage to get a MAC to try to reproduce your issue. Nevertheless, I managed to set up test automation on Travis including OSX OS.

https://travis-ci.org/noxdafox/pebble

All tests are passing successfully. I am pretty confident that the issue you suffer from would have most likely shown itself in the tests as the coverage is pretty good.

This narrows down the issue to your set-up. I wonder what can cause that bad file descriptor. 

Are you, by any chance, terminating the Pool workers manually? 
Is there any specific constraint within your environment?
Did you limit the amount of file descriptors with `ulimit`?

**Comment by e271828-** [comment] 2017-07-21 04:53
@noxdafox I have the same error on a mac when using `ProcessPool`:

`add_done_callback` indicates everything completes successfully.

I believe it's due to using `requests` sessions within the function running via the pool. There's no guarantee that all sessions will be closed at the time the pool process ends.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/pebble/pool/process.py", line 155, in message_manager_loop
    pool_manager.process_next_message(SLEEP_UNIT)
  File "/usr/local/lib/python2.7/site-packages/pebble/pool/process.py", line 184, in process_next_message
    message = self.worker_manager.receive(timeout)
  File "/usr/local/lib/python2.7/site-packages/pebble/pool/process.py", line 304, in receive
    if self.pool_channel.poll(timeout):
  File "/usr/local/lib/python2.7/site-packages/pebble/pool/channel.py", line 44, in unix_poll
    return bool(select([self.reader], [], [], timeout)[0])
error: (9, 'Bad file descriptor')
```

**Comment by noxdafox** [comment] 2017-07-21 11:00
The traceback indicates that the OS pipe used to communicate with the worker processes gets somehow corrupted. 

Are the tasks completed correctly? If so, this might happen when the `ProcessPool` is terminated. In such case, this is just noise which I can silence.

Yet I want to make sure this is not affecting the task processing.

**Comment by e271828-** [comment] 2017-07-21 12:33
@noxdafox The tasks are indeed completed correctly. So far as I can tell it's just noise.

**Comment by noxdafox** [comment] 2017-07-23 09:08
The following [branch](https://github.com/noxdafox/pebble/tree/issue_10) should fix the issue. 

The issue seems to affect only Python 2 and it's due to a [custom select exception](https://docs.python.org/2/library/select.html?highlight=select#select.error) which was not dealt with during the `ProcessPool` shutdown. Hence the noisy traceback.

**Comment by noxdafox** [comment] 2017-07-24 10:00
Patch merged and released in version 4.3.3.

Thanks @e271828- for trying it out.

**Closed by noxdafox** 2017-07-24 10:00 UTC

**Comment by pw717** [comment] 2017-07-24 13:52
Sorry I arrive late since I was on vacation, but version 4.3.3 is also OK for me on the Mac OSX.
Thank-you very much again for your help and yout time !

**Comment by noxdafox** [comment] 2017-07-24 16:02
Np, thank you for reporting the issue!
