### ISSUE TITLE
Pool tasks count

### ISSUE THREAD

**Issue by ghilesmeddour** [noxdafox/pebble#85] opened 2021-09-08 13:25 UTC
Hello,

Thank you for **pebble**.

Is it possible to get different tasks counts (cancelled, running, done) for a given pool. If not, do you think it is a good idea to add it?

Thanks

**Comment by noxdafox** [comment] 2022-05-08 13:54
This is a duplicate of #27.

**Closed by noxdafox** 2022-05-08 13:54 UTC
Labels: duplicate
